included:
  - "Sources"
  - "Tests"
excluded: 
  - ".build"
disabled_rules:
  - todo
  - nesting
  - line_length
  - type_body_length
  - identifier_name
  - file_length
  - force_cast
  - type_name
  - large_tuple
  - function_body_length
  - function_parameter_count
  - cyclomatic_complexity
  - force_try
