name: 'Setup'
description: 'Setup the environment'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Select Xcode 
      run: | 
        sudo xcode-select --switch /Applications/Xcode_16.4.app
    # Docker fails on macos-15 runners with a virtualization error. Until Github supports runners with nested virtualization enabled on macos-15 runners, disable this.
    # - name: Setup Docker on macOS
    #   uses: docker/setup-docker-action@v3
    #   with:
    #     daemon-config: |
    #       {
    #         "debug": true
    #       }
    
    # No Docker: manually setup go
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22' # Or a recent stable version
    
    # No Docker: manually setup node
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    # No Docker: manually download the otel collector 
    - name: Download otel-collector
      shell: bash
      run: |
        cd ${{ github.workspace }}/Tests/ContractTests/MockCollector
        curl --proto '=https' --tlsv1.2 -fOL https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.133.0/otelcol_0.133.0_darwin_arm64.tar.gz
        tar -xvf otelcol_0.133.0_darwin_arm64.tar.gz

  
    

