name: 'Setup'
description: 'Setup the environment'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      shell: bash

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app 
      shell: bash

    - name: Show current version of Xcode
      run: xcodebuild -version
      shell: bash
