name: 'Setup'
description: 'Setup the environment'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    # - name: Setup Docker on macOS
    #   uses: docker/setup-docker-action@v3
    #   with:
    #     daemon-config: |
    #       {
    #         "debug": true
    #       }

    # - name: Verify Docker installation
    #   run: docker info
    #   shell: bash

    # - name: Set up Docker Compose
    #   uses: docker/setup-compose-action@v1
    #   with:
    #     version: 'latest'

    # - name: Set up Docker Compose
    #   shell: bash
    #   run: docker compose version
    

