

name: 'Contract Tests Action'
description: 'Reusable contract tests action with specified iOS SDK version'
inputs:
  api-level:
    description: 'iOS SDK version to use (e.g., 35)'
    required: true

runs:
  using: "composite"
  steps:
    # - name: Install Docker
    #   shell: bash
    #   run: |
    #     # Install Docker on macOS
    #     brew install --cask docker
    #     # Start Docker
    #     open /Applications/Docker.app
    #     # Wait for Docker to start
    #     while ! docker system info > /dev/null 2>&1; do sleep 1; done

    - name: Prepare directory
      shell: bash
      run: |
        sudo mkdir -p /tmp/otel-swift-collector  
        sudo chmod 777 /tmp/otel-swift-collector    

    # - name: Install dependencies (if any)
    #   shell: bash
    #   run: |
    #     # Example: Install CocoaPods dependencies
    #     pod install --repo-update

    - name: Start Mock Collector and Mock Endpoint
      shell: bash
      run: |
        cd ${{ github.workspace }}/Tests/ContractTests/MockCollector
        docker compose up -d  # Run in background
        cd ${{ github.workspace }}

    - name: Generate spans and logs for contract tests
      shell: bash
      run: |
        # ios
        cd ${{ github.workspace }}/Examples/SimpleAwsDemo
        make contract-test-generate-data-ios
        cd ${{ github.workspace }}

        # # tvos
        # cd ${{ github.workspace }}/Examples/SimpleAwsDemo
        # make contract-test-generate-data-tvos
        # cd ${{ github.workspace }}

        # # watchos
        # cd ${{ github.workspace }}/Examples/SimpleAwsDemo
        # make contract-test-generate-data-watchos
        # cd ${{ github.workspace }}

    - uses: actions/upload-artifact@v4
      with:
        name: traces_file-sdk-${{ inputs.api-level }}
        path: /tmp/otel-swift-collector/traces.txt

    - uses: actions/upload-artifact@v4
      with:
        name: logs_file-sdk-${{ inputs.api-level }}
        path: /tmp/otel-swift-collector/logs.txt

    - name: Run contract tests
      shell: bash
      run: |
        make contract-test-run-ios
        # make contract-test-run-tvos
        # make contract-test-run-watchos

  