

name: 'Contract Tests Action'
description: 'Reusable contract tests action with specified iOS SDK version'
inputs:
  api-level:
    description: 'iOS SDK version to use (e.g., 35)'
    required: true

# Remove if using Docker
env:
  MOCK_ENDPOINT_PORT: 8181

runs:
  using: "composite"
  steps:

    - name: Prepare directory
      shell: bash
      run: |
        sudo mkdir -p /tmp/otel-swift-collector  
        sudo chmod 777 /tmp/otel-swift-collector    

    # 
    # - name: Start Mock Collector and Mock Endpoint
    #   shell: bash
    #   run: |
    #     cd ${{ github.workspace }}/Tests/ContractTests/MockCollector
    #     docker compose up -d  # Run in background
    #     cd ${{ github.workspace }}

    # No Docker: manually start otel collector
    - name: Start OpenTelemetry Collector
      run: |
        cd ${{ github.workspace }}/Tests/ContractTests
        ./opentelemetry-collector/otelcorecol --config=./collector.yaml &
        sleep 5 # Give the collector a moment to start
        cd ${{ github.workspace }}

    # No Docker: manually start mock endpoint 
    - name: Start Mock Endpoint
      run: |
        cd ${{ github.workspace }}/Tests/ContractTests/MockCollector/MockEndpoint
        node server.js
        cd ${{ github.workspace }}

    - name: Generate spans and logs for contract tests
      shell: bash
      run: |
        # ios
        cd ${{ github.workspace }}/Examples/SimpleAwsDemo
        make contract-test-generate-data-ios
        cd ${{ github.workspace }}

        # # tvos
        # cd ${{ github.workspace }}/Examples/SimpleAwsDemo
        # make contract-test-generate-data-tvos
        # cd ${{ github.workspace }}

        # # watchos
        # cd ${{ github.workspace }}/Examples/SimpleAwsDemo
        # make contract-test-generate-data-watchos
        # cd ${{ github.workspace }}

    - uses: actions/upload-artifact@v4
      with:
        name: traces_file-sdk-${{ inputs.api-level }}
        path: /tmp/otel-swift-collector/traces.txt

    - uses: actions/upload-artifact@v4
      with:
        name: logs_file-sdk-${{ inputs.api-level }}
        path: /tmp/otel-swift-collector/logs.txt

    - name: Run contract tests
      shell: bash
      run: |
        make contract-test-run-ios
        # make contract-test-run-tvos
        # make contract-test-run-watchos

  